version: 2.1
jobs:
  prepare:
    working_directory: ~/app
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - resotre_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
  build:
    working_directory: ~/app
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: yarn build
      - persist_to_workspace:
          root: ~/app
          paths:
            - extension/build
  package:
    working_directory: ~/app
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run: yarn package
workflows:
  version: 2
  build-test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - package:
          requires:
            - build
          filters:
            branches:
              only:
                - master
